package hdnks.nks.vn.scollautoload;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import retrofit.RestAdapter;
import retrofit.http.GET;
import retrofit.http.Query;

/**
 * Created by loc on 06/08/2015.
 */
/*
*
* {
total_count: 99731,
incomplete_results: false,
items: [
{
id: 8217574,
name: "android-swipelistview",
full_name: "47deg/android-swipelistview",
owner: {
login: "47deg",
id: 479857,
avatar_url: "https://avatars.githubusercontent.com/u/479857?v=3",
gravatar_id: "",
url: "https://api.github.com/users/47deg",
html_url: "https://github.com/47deg",
followers_url: "https://api.github.com/users/47deg/followers",
following_url: "https://api.github.com/users/47deg/following{/other_user}",
gists_url: "https://api.github.com/users/47deg/gists{/gist_id}",
starred_url: "https://api.github.com/users/47deg/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/47deg/subscriptions",
organizations_url: "https://api.github.com/users/47deg/orgs",
repos_url: "https://api.github.com/users/47deg/repos",
events_url: "https://api.github.com/users/47deg/events{/privacy}",
received_events_url: "https://api.github.com/users/47deg/received_events",
type: "Organization",
site_admin: false
},
private: false,
html_url: "https://github.com/47deg/android-swipelistview",
description: "An Android List View implementation with support for drawable cells and many other swipe related features",
fork: false,
url: "https://api.github.com/repos/47deg/android-swipelistview",
forks_url: "https://api.github.com/repos/47deg/android-swipelistview/forks",
keys_url: "https://api.github.com/repos/47deg/android-swipelistview/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/47deg/android-swipelistview/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/47deg/android-swipelistview/teams",
hooks_url: "https://api.github.com/repos/47deg/android-swipelistview/hooks",
issue_events_url: "https://api.github.com/repos/47deg/android-swipelistview/issues/events{/number}",
events_url: "https://api.github.com/repos/47deg/android-swipelistview/events",
assignees_url: "https://api.github.com/repos/47deg/android-swipelistview/assignees{/user}",
branches_url: "https://api.github.com/repos/47deg/android-swipelistview/branches{/branch}",
tags_url: "https://api.github.com/repos/47deg/android-swipelistview/tags",
blobs_url: "https://api.github.com/repos/47deg/android-swipelistview/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/47deg/android-swipelistview/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/47deg/android-swipelistview/git/refs{/sha}",
trees_url: "https://api.github.com/repos/47deg/android-swipelistview/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/47deg/android-swipelistview/statuses/{sha}",
languages_url: "https://api.github.com/repos/47deg/android-swipelistview/languages",
stargazers_url: "https://api.github.com/repos/47deg/android-swipelistview/stargazers",
contributors_url: "https://api.github.com/repos/47deg/android-swipelistview/contributors",
subscribers_url: "https://api.github.com/repos/47deg/android-swipelistview/subscribers",
subscription_url: "https://api.github.com/repos/47deg/android-swipelistview/subscription",
commits_url: "https://api.github.com/repos/47deg/android-swipelistview/commits{/sha}",
git_commits_url: "https://api.github.com/repos/47deg/android-swipelistview/git/commits{/sha}",
comments_url: "https://api.github.com/repos/47deg/android-swipelistview/comments{/number}",
issue_comment_url: "https://api.github.com/repos/47deg/android-swipelistview/issues/comments{/number}",
contents_url: "https://api.github.com/repos/47deg/android-swipelistview/contents/{+path}",
compare_url: "https://api.github.com/repos/47deg/android-swipelistview/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/47deg/android-swipelistview/merges",
archive_url: "https://api.github.com/repos/47deg/android-swipelistview/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/47deg/android-swipelistview/downloads",
issues_url: "https://api.github.com/repos/47deg/android-swipelistview/issues{/number}",
pulls_url: "https://api.github.com/repos/47deg/android-swipelistview/pulls{/number}",
milestones_url: "https://api.github.com/repos/47deg/android-swipelistview/milestones{/number}",
notifications_url: "https://api.github.com/repos/47deg/android-swipelistview/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/47deg/android-swipelistview/labels{/name}",
releases_url: "https://api.github.com/repos/47deg/android-swipelistview/releases{/id}",
created_at: "2013-02-15T11:56:37Z",
updated_at: "2015-08-05T23:22:38Z",
pushed_at: "2015-06-11T06:25:57Z",
git_url: "git://github.com/47deg/android-swipelistview.git",
ssh_url: "git@github.com:47deg/android-swipelistview.git",
clone_url: "https://github.com/47deg/android-swipelistview.git",
svn_url: "https://github.com/47deg/android-swipelistview",
homepage: null,
size: 8593,
stargazers_count: 3001,
watchers_count: 3001,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: true,
has_pages: true,
forks_count: 1389,
mirror_url: null,
open_issues_count: 133,
forks: 1389,
open_issues: 133,
watchers: 3001,
default_branch: "master",
score: 2.6663551
},
{
id: 2626751,
name: "greenDAO",
full_name: "greenrobot/greenDAO",
owner: {
login: "greenrobot",
id: 242242,
avatar_url: "https://avatars.githubusercontent.com/u/242242?v=3",
gravatar_id: "",
url: "https://api.github.com/users/greenrobot",
html_url: "https://github.com/greenrobot",
followers_url: "https://api.github.com/users/greenrobot/followers",
following_url: "https://api.github.com/users/greenrobot/following{/other_user}",
gists_url: "https://api.github.com/users/greenrobot/gists{/gist_id}",
starred_url: "https://api.github.com/users/greenrobot/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/greenrobot/subscriptions",
organizations_url: "https://api.github.com/users/greenrobot/orgs",
repos_url: "https://api.github.com/users/greenrobot/repos",
events_url: "https://api.github.com/users/greenrobot/events{/privacy}",
received_events_url: "https://api.github.com/users/greenrobot/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/greenrobot/greenDAO",
description: "greenDAO is a light & fast ORM solution for Android that maps objects to SQLite databases.",
fork: false,
url: "https://api.github.com/repos/greenrobot/greenDAO",
forks_url: "https://api.github.com/repos/greenrobot/greenDAO/forks",
keys_url: "https://api.github.com/repos/greenrobot/greenDAO/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/greenrobot/greenDAO/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/greenrobot/greenDAO/teams",
hooks_url: "https://api.github.com/repos/greenrobot/greenDAO/hooks",
issue_events_url: "https://api.github.com/repos/greenrobot/greenDAO/issues/events{/number}",
events_url: "https://api.github.com/repos/greenrobot/greenDAO/events",
assignees_url: "https://api.github.com/repos/greenrobot/greenDAO/assignees{/user}",
branches_url: "https://api.github.com/repos/greenrobot/greenDAO/branches{/branch}",
tags_url: "https://api.github.com/repos/greenrobot/greenDAO/tags",
blobs_url: "https://api.github.com/repos/greenrobot/greenDAO/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/greenrobot/greenDAO/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/greenrobot/greenDAO/git/refs{/sha}",
trees_url: "https://api.github.com/repos/greenrobot/greenDAO/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/greenrobot/greenDAO/statuses/{sha}",
languages_url: "https://api.github.com/repos/greenrobot/greenDAO/languages",
stargazers_url: "https://api.github.com/repos/greenrobot/greenDAO/stargazers",
contributors_url: "https://api.github.com/repos/greenrobot/greenDAO/contributors",
subscribers_url: "https://api.github.com/repos/greenrobot/greenDAO/subscribers",
subscription_url: "https://api.github.com/repos/greenrobot/greenDAO/subscription",
commits_url: "https://api.github.com/repos/greenrobot/greenDAO/commits{/sha}",
git_commits_url: "https://api.github.com/repos/greenrobot/greenDAO/git/commits{/sha}",
comments_url: "https://api.github.com/repos/greenrobot/greenDAO/comments{/number}",
issue_comment_url: "https://api.github.com/repos/greenrobot/greenDAO/issues/comments{/number}",
contents_url: "https://api.github.com/repos/greenrobot/greenDAO/contents/{+path}",
compare_url: "https://api.github.com/repos/greenrobot/greenDAO/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/greenrobot/greenDAO/merges",
archive_url: "https://api.github.com/repos/greenrobot/greenDAO/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/greenrobot/greenDAO/downloads",
issues_url: "https://api.github.com/repos/greenrobot/greenDAO/issues{/number}",
pulls_url: "https://api.github.com/repos/greenrobot/greenDAO/pulls{/number}",
milestones_url: "https://api.github.com/repos/greenrobot/greenDAO/milestones{/number}",
notifications_url: "https://api.github.com/repos/greenrobot/greenDAO/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/greenrobot/greenDAO/labels{/name}",
releases_url: "https://api.github.com/repos/greenrobot/greenDAO/releases{/id}",
created_at: "2011-10-22T16:15:14Z",
updated_at: "2015-08-05T23:57:42Z",
pushed_at: "2015-07-31T21:44:32Z",
git_url: "git://github.com/greenrobot/greenDAO.git",
ssh_url: "git@github.com:greenrobot/greenDAO.git",
clone_url: "https://github.com/greenrobot/greenDAO.git",
svn_url: "https://github.com/greenrobot/greenDAO",
homepage: "http://greendao-orm.com/",
size: 11864,
stargazers_count: 2809,
watchers_count: 2809,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: false,
has_pages: false,
forks_count: 1117,
mirror_url: null,
open_issues_count: 91,
forks: 1117,
open_issues: 91,
watchers: 2809,
default_branch: "master",
score: 2.6479318
},
{
id: 6709149,
name: "ActiveAndroid",
full_name: "pardom/ActiveAndroid",
owner: {
login: "pardom",
id: 189503,
avatar_url: "https://avatars.githubusercontent.com/u/189503?v=3",
gravatar_id: "",
url: "https://api.github.com/users/pardom",
html_url: "https://github.com/pardom",
followers_url: "https://api.github.com/users/pardom/followers",
following_url: "https://api.github.com/users/pardom/following{/other_user}",
gists_url: "https://api.github.com/users/pardom/gists{/gist_id}",
starred_url: "https://api.github.com/users/pardom/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/pardom/subscriptions",
organizations_url: "https://api.github.com/users/pardom/orgs",
repos_url: "https://api.github.com/users/pardom/repos",
events_url: "https://api.github.com/users/pardom/events{/privacy}",
received_events_url: "https://api.github.com/users/pardom/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/pardom/ActiveAndroid",
description: "Active record style SQLite persistence for Android",
fork: false,
url: "https://api.github.com/repos/pardom/ActiveAndroid",
forks_url: "https://api.github.com/repos/pardom/ActiveAndroid/forks",
keys_url: "https://api.github.com/repos/pardom/ActiveAndroid/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/pardom/ActiveAndroid/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/pardom/ActiveAndroid/teams",
hooks_url: "https://api.github.com/repos/pardom/ActiveAndroid/hooks",
issue_events_url: "https://api.github.com/repos/pardom/ActiveAndroid/issues/events{/number}",
events_url: "https://api.github.com/repos/pardom/ActiveAndroid/events",
assignees_url: "https://api.github.com/repos/pardom/ActiveAndroid/assignees{/user}",
branches_url: "https://api.github.com/repos/pardom/ActiveAndroid/branches{/branch}",
tags_url: "https://api.github.com/repos/pardom/ActiveAndroid/tags",
blobs_url: "https://api.github.com/repos/pardom/ActiveAndroid/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/pardom/ActiveAndroid/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/pardom/ActiveAndroid/git/refs{/sha}",
trees_url: "https://api.github.com/repos/pardom/ActiveAndroid/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/pardom/ActiveAndroid/statuses/{sha}",
languages_url: "https://api.github.com/repos/pardom/ActiveAndroid/languages",
stargazers_url: "https://api.github.com/repos/pardom/ActiveAndroid/stargazers",
contributors_url: "https://api.github.com/repos/pardom/ActiveAndroid/contributors",
subscribers_url: "https://api.github.com/repos/pardom/ActiveAndroid/subscribers",
subscription_url: "https://api.github.com/repos/pardom/ActiveAndroid/subscription",
commits_url: "https://api.github.com/repos/pardom/ActiveAndroid/commits{/sha}",
git_commits_url: "https://api.github.com/repos/pardom/ActiveAndroid/git/commits{/sha}",
comments_url: "https://api.github.com/repos/pardom/ActiveAndroid/comments{/number}",
issue_comment_url: "https://api.github.com/repos/pardom/ActiveAndroid/issues/comments{/number}",
contents_url: "https://api.github.com/repos/pardom/ActiveAndroid/contents/{+path}",
compare_url: "https://api.github.com/repos/pardom/ActiveAndroid/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/pardom/ActiveAndroid/merges",
archive_url: "https://api.github.com/repos/pardom/ActiveAndroid/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/pardom/ActiveAndroid/downloads",
issues_url: "https://api.github.com/repos/pardom/ActiveAndroid/issues{/number}",
pulls_url: "https://api.github.com/repos/pardom/ActiveAndroid/pulls{/number}",
milestones_url: "https://api.github.com/repos/pardom/ActiveAndroid/milestones{/number}",
notifications_url: "https://api.github.com/repos/pardom/ActiveAndroid/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/pardom/ActiveAndroid/labels{/name}",
releases_url: "https://api.github.com/repos/pardom/ActiveAndroid/releases{/id}",
created_at: "2012-11-15T18:10:45Z",
updated_at: "2015-08-05T14:09:09Z",
pushed_at: "2015-08-03T07:15:44Z",
git_url: "git://github.com/pardom/ActiveAndroid.git",
ssh_url: "git@github.com:pardom/ActiveAndroid.git",
clone_url: "https://github.com/pardom/ActiveAndroid.git",
svn_url: "https://github.com/pardom/ActiveAndroid",
homepage: "http://www.activeandroid.com",
size: 18923,
stargazers_count: 2771,
watchers_count: 2771,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: true,
has_pages: true,
forks_count: 749,
mirror_url: null,
open_issues_count: 205,
forks: 749,
open_issues: 205,
watchers: 2771,
default_branch: "master",
score: 4.266168
},
{
id: 11704709,
name: "xUtils",
full_name: "wyouflf/xUtils",
owner: {
login: "wyouflf",
id: 2654372,
avatar_url: "https://avatars.githubusercontent.com/u/2654372?v=3",
gravatar_id: "",
url: "https://api.github.com/users/wyouflf",
html_url: "https://github.com/wyouflf",
followers_url: "https://api.github.com/users/wyouflf/followers",
following_url: "https://api.github.com/users/wyouflf/following{/other_user}",
gists_url: "https://api.github.com/users/wyouflf/gists{/gist_id}",
starred_url: "https://api.github.com/users/wyouflf/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/wyouflf/subscriptions",
organizations_url: "https://api.github.com/users/wyouflf/orgs",
repos_url: "https://api.github.com/users/wyouflf/repos",
events_url: "https://api.github.com/users/wyouflf/events{/privacy}",
received_events_url: "https://api.github.com/users/wyouflf/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/wyouflf/xUtils",
description: "android orm, bitmap, http, view inject... ",
fork: false,
url: "https://api.github.com/repos/wyouflf/xUtils",
forks_url: "https://api.github.com/repos/wyouflf/xUtils/forks",
keys_url: "https://api.github.com/repos/wyouflf/xUtils/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/wyouflf/xUtils/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/wyouflf/xUtils/teams",
hooks_url: "https://api.github.com/repos/wyouflf/xUtils/hooks",
issue_events_url: "https://api.github.com/repos/wyouflf/xUtils/issues/events{/number}",
events_url: "https://api.github.com/repos/wyouflf/xUtils/events",
assignees_url: "https://api.github.com/repos/wyouflf/xUtils/assignees{/user}",
branches_url: "https://api.github.com/repos/wyouflf/xUtils/branches{/branch}",
tags_url: "https://api.github.com/repos/wyouflf/xUtils/tags",
blobs_url: "https://api.github.com/repos/wyouflf/xUtils/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/wyouflf/xUtils/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/wyouflf/xUtils/git/refs{/sha}",
trees_url: "https://api.github.com/repos/wyouflf/xUtils/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/wyouflf/xUtils/statuses/{sha}",
languages_url: "https://api.github.com/repos/wyouflf/xUtils/languages",
stargazers_url: "https://api.github.com/repos/wyouflf/xUtils/stargazers",
contributors_url: "https://api.github.com/repos/wyouflf/xUtils/contributors",
subscribers_url: "https://api.github.com/repos/wyouflf/xUtils/subscribers",
subscription_url: "https://api.github.com/repos/wyouflf/xUtils/subscription",
commits_url: "https://api.github.com/repos/wyouflf/xUtils/commits{/sha}",
git_commits_url: "https://api.github.com/repos/wyouflf/xUtils/git/commits{/sha}",
comments_url: "https://api.github.com/repos/wyouflf/xUtils/comments{/number}",
issue_comment_url: "https://api.github.com/repos/wyouflf/xUtils/issues/comments{/number}",
contents_url: "https://api.github.com/repos/wyouflf/xUtils/contents/{+path}",
compare_url: "https://api.github.com/repos/wyouflf/xUtils/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/wyouflf/xUtils/merges",
archive_url: "https://api.github.com/repos/wyouflf/xUtils/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/wyouflf/xUtils/downloads",
issues_url: "https://api.github.com/repos/wyouflf/xUtils/issues{/number}",
pulls_url: "https://api.github.com/repos/wyouflf/xUtils/pulls{/number}",
milestones_url: "https://api.github.com/repos/wyouflf/xUtils/milestones{/number}",
notifications_url: "https://api.github.com/repos/wyouflf/xUtils/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/wyouflf/xUtils/labels{/name}",
releases_url: "https://api.github.com/repos/wyouflf/xUtils/releases{/id}",
created_at: "2013-07-27T12:37:01Z",
updated_at: "2015-08-05T16:03:32Z",
pushed_at: "2015-08-06T00:02:30Z",
git_url: "git://github.com/wyouflf/xUtils.git",
ssh_url: "git@github.com:wyouflf/xUtils.git",
clone_url: "https://github.com/wyouflf/xUtils.git",
svn_url: "https://github.com/wyouflf/xUtils",
homepage: "",
size: 51621,
stargazers_count: 2755,
watchers_count: 2755,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: true,
has_pages: false,
forks_count: 2022,
mirror_url: null,
open_issues_count: 137,
forks: 2022,
open_issues: 137,
watchers: 2755,
default_branch: "master",
score: 4.236691
},
{
id: 2942615,
name: "NineOldAndroids",
full_name: "JakeWharton/NineOldAndroids",
owner: {
login: "JakeWharton",
id: 66577,
avatar_url: "https://avatars.githubusercontent.com/u/66577?v=3",
gravatar_id: "",
url: "https://api.github.com/users/JakeWharton",
html_url: "https://github.com/JakeWharton",
followers_url: "https://api.github.com/users/JakeWharton/followers",
following_url: "https://api.github.com/users/JakeWharton/following{/other_user}",
gists_url: "https://api.github.com/users/JakeWharton/gists{/gist_id}",
starred_url: "https://api.github.com/users/JakeWharton/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/JakeWharton/subscriptions",
organizations_url: "https://api.github.com/users/JakeWharton/orgs",
repos_url: "https://api.github.com/users/JakeWharton/repos",
events_url: "https://api.github.com/users/JakeWharton/events{/privacy}",
received_events_url: "https://api.github.com/users/JakeWharton/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/JakeWharton/NineOldAndroids",
description: "[DEPRECATED] Android library for using the Honeycomb animation API on all versions of the platform back to 1.0!",
fork: false,
url: "https://api.github.com/repos/JakeWharton/NineOldAndroids",
forks_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/forks",
keys_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/teams",
hooks_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/hooks",
issue_events_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/issues/events{/number}",
events_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/events",
assignees_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/assignees{/user}",
branches_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/branches{/branch}",
tags_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/tags",
blobs_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/git/refs{/sha}",
trees_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/statuses/{sha}",
languages_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/languages",
stargazers_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/stargazers",
contributors_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/contributors",
subscribers_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/subscribers",
subscription_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/subscription",
commits_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/commits{/sha}",
git_commits_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/git/commits{/sha}",
comments_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/comments{/number}",
issue_comment_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/issues/comments{/number}",
contents_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/contents/{+path}",
compare_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/merges",
archive_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/downloads",
issues_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/issues{/number}",
pulls_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/pulls{/number}",
milestones_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/milestones{/number}",
notifications_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/labels{/name}",
releases_url: "https://api.github.com/repos/JakeWharton/NineOldAndroids/releases{/id}",
created_at: "2011-12-08T19:46:37Z",
updated_at: "2015-08-05T23:42:46Z",
pushed_at: "2015-04-27T19:14:09Z",
git_url: "git://github.com/JakeWharton/NineOldAndroids.git",
ssh_url: "git@github.com:JakeWharton/NineOldAndroids.git",
clone_url: "https://github.com/JakeWharton/NineOldAndroids.git",
svn_url: "https://github.com/JakeWharton/NineOldAndroids",
homepage: "http://nineoldandroids.com",
size: 1208,
stargazers_count: 2695,
watchers_count: 2695,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: false,
has_pages: true,
forks_count: 1285,
mirror_url: null,
open_issues_count: 37,
forks: 1285,
open_issues: 37,
watchers: 2695,
default_branch: "master",
score: 2.6479318
},
{
id: 5284389,
name: "Crouton",
full_name: "keyboardsurfer/Crouton",
owner: {
login: "keyboardsurfer",
id: 336005,
avatar_url: "https://avatars.githubusercontent.com/u/336005?v=3",
gravatar_id: "",
url: "https://api.github.com/users/keyboardsurfer",
html_url: "https://github.com/keyboardsurfer",
followers_url: "https://api.github.com/users/keyboardsurfer/followers",
following_url: "https://api.github.com/users/keyboardsurfer/following{/other_user}",
gists_url: "https://api.github.com/users/keyboardsurfer/gists{/gist_id}",
starred_url: "https://api.github.com/users/keyboardsurfer/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/keyboardsurfer/subscriptions",
organizations_url: "https://api.github.com/users/keyboardsurfer/orgs",
repos_url: "https://api.github.com/users/keyboardsurfer/repos",
events_url: "https://api.github.com/users/keyboardsurfer/events{/privacy}",
received_events_url: "https://api.github.com/users/keyboardsurfer/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/keyboardsurfer/Crouton",
description: "Context sensitive notifications for Android ",
fork: false,
url: "https://api.github.com/repos/keyboardsurfer/Crouton",
forks_url: "https://api.github.com/repos/keyboardsurfer/Crouton/forks",
keys_url: "https://api.github.com/repos/keyboardsurfer/Crouton/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/keyboardsurfer/Crouton/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/keyboardsurfer/Crouton/teams",
hooks_url: "https://api.github.com/repos/keyboardsurfer/Crouton/hooks",
issue_events_url: "https://api.github.com/repos/keyboardsurfer/Crouton/issues/events{/number}",
events_url: "https://api.github.com/repos/keyboardsurfer/Crouton/events",
assignees_url: "https://api.github.com/repos/keyboardsurfer/Crouton/assignees{/user}",
branches_url: "https://api.github.com/repos/keyboardsurfer/Crouton/branches{/branch}",
tags_url: "https://api.github.com/repos/keyboardsurfer/Crouton/tags",
blobs_url: "https://api.github.com/repos/keyboardsurfer/Crouton/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/keyboardsurfer/Crouton/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/keyboardsurfer/Crouton/git/refs{/sha}",
trees_url: "https://api.github.com/repos/keyboardsurfer/Crouton/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/keyboardsurfer/Crouton/statuses/{sha}",
languages_url: "https://api.github.com/repos/keyboardsurfer/Crouton/languages",
stargazers_url: "https://api.github.com/repos/keyboardsurfer/Crouton/stargazers",
contributors_url: "https://api.github.com/repos/keyboardsurfer/Crouton/contributors",
subscribers_url: "https://api.github.com/repos/keyboardsurfer/Crouton/subscribers",
subscription_url: "https://api.github.com/repos/keyboardsurfer/Crouton/subscription",
commits_url: "https://api.github.com/repos/keyboardsurfer/Crouton/commits{/sha}",
git_commits_url: "https://api.github.com/repos/keyboardsurfer/Crouton/git/commits{/sha}",
comments_url: "https://api.github.com/repos/keyboardsurfer/Crouton/comments{/number}",
issue_comment_url: "https://api.github.com/repos/keyboardsurfer/Crouton/issues/comments{/number}",
contents_url: "https://api.github.com/repos/keyboardsurfer/Crouton/contents/{+path}",
compare_url: "https://api.github.com/repos/keyboardsurfer/Crouton/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/keyboardsurfer/Crouton/merges",
archive_url: "https://api.github.com/repos/keyboardsurfer/Crouton/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/keyboardsurfer/Crouton/downloads",
issues_url: "https://api.github.com/repos/keyboardsurfer/Crouton/issues{/number}",
pulls_url: "https://api.github.com/repos/keyboardsurfer/Crouton/pulls{/number}",
milestones_url: "https://api.github.com/repos/keyboardsurfer/Crouton/milestones{/number}",
notifications_url: "https://api.github.com/repos/keyboardsurfer/Crouton/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/keyboardsurfer/Crouton/labels{/name}",
releases_url: "https://api.github.com/repos/keyboardsurfer/Crouton/releases{/id}",
created_at: "2012-08-03T11:04:36Z",
updated_at: "2015-08-05T21:42:43Z",
pushed_at: "2015-06-05T17:20:37Z",
git_url: "git://github.com/keyboardsurfer/Crouton.git",
ssh_url: "git@github.com:keyboardsurfer/Crouton.git",
clone_url: "https://github.com/keyboardsurfer/Crouton.git",
svn_url: "https://github.com/keyboardsurfer/Crouton",
homepage: null,
size: 3496,
stargazers_count: 2596,
watchers_count: 2596,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: true,
has_pages: true,
forks_count: 685,
mirror_url: null,
open_issues_count: 3,
forks: 685,
open_issues: 3,
watchers: 2596,
default_branch: "master",
score: 4.236691
},
{
id: 2828194,
name: "AndEngine",
full_name: "nicolasgramlich/AndEngine",
owner: {
login: "nicolasgramlich",
id: 287060,
avatar_url: "https://avatars.githubusercontent.com/u/287060?v=3",
gravatar_id: "",
url: "https://api.github.com/users/nicolasgramlich",
html_url: "https://github.com/nicolasgramlich",
followers_url: "https://api.github.com/users/nicolasgramlich/followers",
following_url: "https://api.github.com/users/nicolasgramlich/following{/other_user}",
gists_url: "https://api.github.com/users/nicolasgramlich/gists{/gist_id}",
starred_url: "https://api.github.com/users/nicolasgramlich/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/nicolasgramlich/subscriptions",
organizations_url: "https://api.github.com/users/nicolasgramlich/orgs",
repos_url: "https://api.github.com/users/nicolasgramlich/repos",
events_url: "https://api.github.com/users/nicolasgramlich/events{/privacy}",
received_events_url: "https://api.github.com/users/nicolasgramlich/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/nicolasgramlich/AndEngine",
description: "Free Android 2D OpenGL Game Engine",
fork: false,
url: "https://api.github.com/repos/nicolasgramlich/AndEngine",
forks_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/forks",
keys_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/teams",
hooks_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/hooks",
issue_events_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/issues/events{/number}",
events_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/events",
assignees_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/assignees{/user}",
branches_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/branches{/branch}",
tags_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/tags",
blobs_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/git/refs{/sha}",
trees_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/statuses/{sha}",
languages_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/languages",
stargazers_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/stargazers",
contributors_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/contributors",
subscribers_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/subscribers",
subscription_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/subscription",
commits_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/commits{/sha}",
git_commits_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/git/commits{/sha}",
comments_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/comments{/number}",
issue_comment_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/issues/comments{/number}",
contents_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/contents/{+path}",
compare_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/merges",
archive_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/downloads",
issues_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/issues{/number}",
pulls_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/pulls{/number}",
milestones_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/milestones{/number}",
notifications_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/labels{/name}",
releases_url: "https://api.github.com/repos/nicolasgramlich/AndEngine/releases{/id}",
created_at: "2011-11-22T14:20:11Z",
updated_at: "2015-08-05T22:34:37Z",
pushed_at: "2015-06-06T16:27:53Z",
git_url: "git://github.com/nicolasgramlich/AndEngine.git",
ssh_url: "git@github.com:nicolasgramlich/AndEngine.git",
clone_url: "https://github.com/nicolasgramlich/AndEngine.git",
svn_url: "https://github.com/nicolasgramlich/AndEngine",
homepage: "http://www.andengine.org",
size: 24111,
stargazers_count: 2581,
watchers_count: 2581,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: true,
has_pages: false,
forks_count: 1461,
mirror_url: null,
open_issues_count: 119,
forks: 1461,
open_issues: 119,
watchers: 2581,
default_branch: "GLES2",
score: 4.266168
},
{
id: 5537121,
name: "AndroidAsync",
full_name: "koush/AndroidAsync",
owner: {
login: "koush",
id: 73924,
avatar_url: "https://avatars.githubusercontent.com/u/73924?v=3",
gravatar_id: "",
url: "https://api.github.com/users/koush",
html_url: "https://github.com/koush",
followers_url: "https://api.github.com/users/koush/followers",
following_url: "https://api.github.com/users/koush/following{/other_user}",
gists_url: "https://api.github.com/users/koush/gists{/gist_id}",
starred_url: "https://api.github.com/users/koush/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/koush/subscriptions",
organizations_url: "https://api.github.com/users/koush/orgs",
repos_url: "https://api.github.com/users/koush/repos",
events_url: "https://api.github.com/users/koush/events{/privacy}",
received_events_url: "https://api.github.com/users/koush/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/koush/AndroidAsync",
description: "Asynchronous socket, http (client+server), websocket, and socket.io library for android. Based on nio, not threads.",
fork: false,
url: "https://api.github.com/repos/koush/AndroidAsync",
forks_url: "https://api.github.com/repos/koush/AndroidAsync/forks",
keys_url: "https://api.github.com/repos/koush/AndroidAsync/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/koush/AndroidAsync/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/koush/AndroidAsync/teams",
hooks_url: "https://api.github.com/repos/koush/AndroidAsync/hooks",
issue_events_url: "https://api.github.com/repos/koush/AndroidAsync/issues/events{/number}",
events_url: "https://api.github.com/repos/koush/AndroidAsync/events",
assignees_url: "https://api.github.com/repos/koush/AndroidAsync/assignees{/user}",
branches_url: "https://api.github.com/repos/koush/AndroidAsync/branches{/branch}",
tags_url: "https://api.github.com/repos/koush/AndroidAsync/tags",
blobs_url: "https://api.github.com/repos/koush/AndroidAsync/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/koush/AndroidAsync/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/koush/AndroidAsync/git/refs{/sha}",
trees_url: "https://api.github.com/repos/koush/AndroidAsync/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/koush/AndroidAsync/statuses/{sha}",
languages_url: "https://api.github.com/repos/koush/AndroidAsync/languages",
stargazers_url: "https://api.github.com/repos/koush/AndroidAsync/stargazers",
contributors_url: "https://api.github.com/repos/koush/AndroidAsync/contributors",
subscribers_url: "https://api.github.com/repos/koush/AndroidAsync/subscribers",
subscription_url: "https://api.github.com/repos/koush/AndroidAsync/subscription",
commits_url: "https://api.github.com/repos/koush/AndroidAsync/commits{/sha}",
git_commits_url: "https://api.github.com/repos/koush/AndroidAsync/git/commits{/sha}",
comments_url: "https://api.github.com/repos/koush/AndroidAsync/comments{/number}",
issue_comment_url: "https://api.github.com/repos/koush/AndroidAsync/issues/comments{/number}",
contents_url: "https://api.github.com/repos/koush/AndroidAsync/contents/{+path}",
compare_url: "https://api.github.com/repos/koush/AndroidAsync/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/koush/AndroidAsync/merges",
archive_url: "https://api.github.com/repos/koush/AndroidAsync/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/koush/AndroidAsync/downloads",
issues_url: "https://api.github.com/repos/koush/AndroidAsync/issues{/number}",
pulls_url: "https://api.github.com/repos/koush/AndroidAsync/pulls{/number}",
milestones_url: "https://api.github.com/repos/koush/AndroidAsync/milestones{/number}",
notifications_url: "https://api.github.com/repos/koush/AndroidAsync/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/koush/AndroidAsync/labels{/name}",
releases_url: "https://api.github.com/repos/koush/AndroidAsync/releases{/id}",
created_at: "2012-08-24T07:27:04Z",
updated_at: "2015-08-05T22:58:17Z",
pushed_at: "2015-08-01T22:47:12Z",
git_url: "git://github.com/koush/AndroidAsync.git",
ssh_url: "git@github.com:koush/AndroidAsync.git",
clone_url: "https://github.com/koush/AndroidAsync.git",
svn_url: "https://github.com/koush/AndroidAsync",
homepage: "",
size: 6712,
stargazers_count: 2581,
watchers_count: 2581,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: false,
has_pages: false,
forks_count: 735,
mirror_url: null,
open_issues_count: 131,
forks: 735,
open_issues: 131,
watchers: 2581,
default_branch: "master",
score: 2.6663551
},
{
id: 36814724,
name: "AppIntro",
full_name: "PaoloRotolo/AppIntro",
owner: {
login: "PaoloRotolo",
id: 5623301,
avatar_url: "https://avatars.githubusercontent.com/u/5623301?v=3",
gravatar_id: "",
url: "https://api.github.com/users/PaoloRotolo",
html_url: "https://github.com/PaoloRotolo",
followers_url: "https://api.github.com/users/PaoloRotolo/followers",
following_url: "https://api.github.com/users/PaoloRotolo/following{/other_user}",
gists_url: "https://api.github.com/users/PaoloRotolo/gists{/gist_id}",
starred_url: "https://api.github.com/users/PaoloRotolo/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/PaoloRotolo/subscriptions",
organizations_url: "https://api.github.com/users/PaoloRotolo/orgs",
repos_url: "https://api.github.com/users/PaoloRotolo/repos",
events_url: "https://api.github.com/users/PaoloRotolo/events{/privacy}",
received_events_url: "https://api.github.com/users/PaoloRotolo/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/PaoloRotolo/AppIntro",
description: "Make a cool intro for your Android app.",
fork: false,
url: "https://api.github.com/repos/PaoloRotolo/AppIntro",
forks_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/forks",
keys_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/teams",
hooks_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/hooks",
issue_events_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/issues/events{/number}",
events_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/events",
assignees_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/assignees{/user}",
branches_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/branches{/branch}",
tags_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/tags",
blobs_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/git/refs{/sha}",
trees_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/statuses/{sha}",
languages_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/languages",
stargazers_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/stargazers",
contributors_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/contributors",
subscribers_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/subscribers",
subscription_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/subscription",
commits_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/commits{/sha}",
git_commits_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/git/commits{/sha}",
comments_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/comments{/number}",
issue_comment_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/issues/comments{/number}",
contents_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/contents/{+path}",
compare_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/merges",
archive_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/downloads",
issues_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/issues{/number}",
pulls_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/pulls{/number}",
milestones_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/milestones{/number}",
notifications_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/labels{/name}",
releases_url: "https://api.github.com/repos/PaoloRotolo/AppIntro/releases{/id}",
created_at: "2015-06-03T16:02:10Z",
updated_at: "2015-08-05T20:42:06Z",
pushed_at: "2015-08-04T19:43:54Z",
git_url: "git://github.com/PaoloRotolo/AppIntro.git",
ssh_url: "git@github.com:PaoloRotolo/AppIntro.git",
clone_url: "https://github.com/PaoloRotolo/AppIntro.git",
svn_url: "https://github.com/PaoloRotolo/AppIntro",
homepage: "",
size: 9938,
stargazers_count: 2566,
watchers_count: 2566,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: true,
has_pages: false,
forks_count: 310,
mirror_url: null,
open_issues_count: 2,
forks: 310,
open_issues: 2,
watchers: 2566,
default_branch: "master",
score: 3.7071047
},
{
id: 22105003,
name: "FloatingActionButton",
full_name: "makovkastar/FloatingActionButton",
owner: {
login: "makovkastar",
id: 1076309,
avatar_url: "https://avatars.githubusercontent.com/u/1076309?v=3",
gravatar_id: "",
url: "https://api.github.com/users/makovkastar",
html_url: "https://github.com/makovkastar",
followers_url: "https://api.github.com/users/makovkastar/followers",
following_url: "https://api.github.com/users/makovkastar/following{/other_user}",
gists_url: "https://api.github.com/users/makovkastar/gists{/gist_id}",
starred_url: "https://api.github.com/users/makovkastar/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/makovkastar/subscriptions",
organizations_url: "https://api.github.com/users/makovkastar/orgs",
repos_url: "https://api.github.com/users/makovkastar/repos",
events_url: "https://api.github.com/users/makovkastar/events{/privacy}",
received_events_url: "https://api.github.com/users/makovkastar/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/makovkastar/FloatingActionButton",
description: "Android floating action button",
fork: false,
url: "https://api.github.com/repos/makovkastar/FloatingActionButton",
forks_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/forks",
keys_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/teams",
hooks_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/hooks",
issue_events_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/issues/events{/number}",
events_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/events",
assignees_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/assignees{/user}",
branches_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/branches{/branch}",
tags_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/tags",
blobs_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/git/refs{/sha}",
trees_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/statuses/{sha}",
languages_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/languages",
stargazers_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/stargazers",
contributors_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/contributors",
subscribers_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/subscribers",
subscription_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/subscription",
commits_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/commits{/sha}",
git_commits_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/git/commits{/sha}",
comments_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/comments{/number}",
issue_comment_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/issues/comments{/number}",
contents_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/contents/{+path}",
compare_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/merges",
archive_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/downloads",
issues_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/issues{/number}",
pulls_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/pulls{/number}",
milestones_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/milestones{/number}",
notifications_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/labels{/name}",
releases_url: "https://api.github.com/repos/makovkastar/FloatingActionButton/releases{/id}",
created_at: "2014-07-22T13:29:55Z",
updated_at: "2015-08-06T01:55:37Z",
pushed_at: "2015-07-06T16:25:11Z",
git_url: "git://github.com/makovkastar/FloatingActionButton.git",
ssh_url: "git@github.com:makovkastar/FloatingActionButton.git",
clone_url: "https://github.com/makovkastar/FloatingActionButton.git",
svn_url: "https://github.com/makovkastar/FloatingActionButton",
homepage: "",
size: 12221,
stargazers_count: 2549,
watchers_count: 2549,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: true,
has_pages: false,
forks_count: 587,
mirror_url: null,
open_issues_count: 65,
forks: 587,
open_issues: 65,
watchers: 2549,
default_branch: "master",
score: 5.2958636
},
{
id: 656893,
name: "GreenDroid",
full_name: "cyrilmottier/GreenDroid",
owner: {
login: "cyrilmottier",
id: 92794,
avatar_url: "https://avatars.githubusercontent.com/u/92794?v=3",
gravatar_id: "",
url: "https://api.github.com/users/cyrilmottier",
html_url: "https://github.com/cyrilmottier",
followers_url: "https://api.github.com/users/cyrilmottier/followers",
following_url: "https://api.github.com/users/cyrilmottier/following{/other_user}",
gists_url: "https://api.github.com/users/cyrilmottier/gists{/gist_id}",
starred_url: "https://api.github.com/users/cyrilmottier/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/cyrilmottier/subscriptions",
organizations_url: "https://api.github.com/users/cyrilmottier/orgs",
repos_url: "https://api.github.com/users/cyrilmottier/repos",
events_url: "https://api.github.com/users/cyrilmottier/events{/privacy}",
received_events_url: "https://api.github.com/users/cyrilmottier/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/cyrilmottier/GreenDroid",
description: "GreenDroid is a development library for the Android platform. It makes UI developments easier and consistent through your applications.",
fork: false,
url: "https://api.github.com/repos/cyrilmottier/GreenDroid",
forks_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/forks",
keys_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/teams",
hooks_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/hooks",
issue_events_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/issues/events{/number}",
events_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/events",
assignees_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/assignees{/user}",
branches_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/branches{/branch}",
tags_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/tags",
blobs_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/git/refs{/sha}",
trees_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/statuses/{sha}",
languages_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/languages",
stargazers_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/stargazers",
contributors_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/contributors",
subscribers_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/subscribers",
subscription_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/subscription",
commits_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/commits{/sha}",
git_commits_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/git/commits{/sha}",
comments_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/comments{/number}",
issue_comment_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/issues/comments{/number}",
contents_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/contents/{+path}",
compare_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/merges",
archive_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/downloads",
issues_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/issues{/number}",
pulls_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/pulls{/number}",
milestones_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/milestones{/number}",
notifications_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/labels{/name}",
releases_url: "https://api.github.com/repos/cyrilmottier/GreenDroid/releases{/id}",
created_at: "2010-05-08T20:31:52Z",
updated_at: "2015-08-05T21:44:41Z",
pushed_at: "2013-07-24T07:16:04Z",
git_url: "git://github.com/cyrilmottier/GreenDroid.git",
ssh_url: "git@github.com:cyrilmottier/GreenDroid.git",
clone_url: "https://github.com/cyrilmottier/GreenDroid.git",
svn_url: "https://github.com/cyrilmottier/GreenDroid",
homepage: "http://www.cyrilmottier.com",
size: 1914,
stargazers_count: 2528,
watchers_count: 2528,
language: "Java",
has_issues: false,
has_downloads: true,
has_wiki: false,
has_pages: false,
forks_count: 1005,
mirror_url: null,
open_issues_count: 55,
forks: 1005,
open_issues: 55,
watchers: 2528,
default_branch: "master",
score: 2.6479318
},
{
id: 26568234,
name: "android-Ultra-Pull-To-Refresh",
full_name: "liaohuqiu/android-Ultra-Pull-To-Refresh",
owner: {
login: "liaohuqiu",
id: 4088573,
avatar_url: "https://avatars.githubusercontent.com/u/4088573?v=3",
gravatar_id: "",
url: "https://api.github.com/users/liaohuqiu",
html_url: "https://github.com/liaohuqiu",
followers_url: "https://api.github.com/users/liaohuqiu/followers",
following_url: "https://api.github.com/users/liaohuqiu/following{/other_user}",
gists_url: "https://api.github.com/users/liaohuqiu/gists{/gist_id}",
starred_url: "https://api.github.com/users/liaohuqiu/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/liaohuqiu/subscriptions",
organizations_url: "https://api.github.com/users/liaohuqiu/orgs",
repos_url: "https://api.github.com/users/liaohuqiu/repos",
events_url: "https://api.github.com/users/liaohuqiu/events{/privacy}",
received_events_url: "https://api.github.com/users/liaohuqiu/received_events",
type: "User",
site_admin: false
},
private: false,
html_url: "https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh",
description: "Ultra Pull to Refresh for Android. Support all the views.",
fork: false,
url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh",
forks_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/forks",
keys_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/keys{/key_id}",
collaborators_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/collaborators{/collaborator}",
teams_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/teams",
hooks_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/hooks",
issue_events_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/events{/number}",
events_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/events",
assignees_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/assignees{/user}",
branches_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/branches{/branch}",
tags_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/tags",
blobs_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/git/blobs{/sha}",
git_tags_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/git/tags{/sha}",
git_refs_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/git/refs{/sha}",
trees_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/git/trees{/sha}",
statuses_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/statuses/{sha}",
languages_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/languages",
stargazers_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/stargazers",
contributors_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/contributors",
subscribers_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/subscribers",
subscription_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/subscription",
commits_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/commits{/sha}",
git_commits_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/git/commits{/sha}",
comments_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/comments{/number}",
issue_comment_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/issues/comments{/number}",
contents_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/contents/{+path}",
compare_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/compare/{base}...{head}",
merges_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/merges",
archive_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/{archive_format}{/ref}",
downloads_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/downloads",
issues_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/issues{/number}",
pulls_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/pulls{/number}",
milestones_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/milestones{/number}",
notifications_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/notifications{?since,all,participating}",
labels_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/labels{/name}",
releases_url: "https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/releases{/id}",
created_at: "2014-11-13T03:13:10Z",
updated_at: "2015-08-06T01:02:06Z",
pushed_at: "2015-07-29T05:50:28Z",
git_url: "git://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh.git",
ssh_url: "git@github.com:liaohuqiu/android-Ultra-Pull-To-Refresh.git",
clone_url: "https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh.git",
svn_url: "https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh",
homepage: "http://android-ultra-ptr.liaohuqiu.net/",
size: 4463,
stargazers_count: 2524,
watchers_count: 2524,
language: "Java",
has_issues: true,
has_downloads: true,
has_wiki: true,
has_pages: false,
forks_count: 832,
mirror_url: null,
open_issues_count: 28,
forks: 832,
open_issues: 28,
watchers: 2524,
default_branch: "master",
score: 3.732897
}
]
}
*
*
*
* */
//  khởi tạo một lớp github client
public class GitHubClient {
    //  k

    // nơi chứa tất cả các đường link
    private static final String API_URL = "https://api.github.com";
    //sort the github repos by stars in desc order
    static final String DEFAULT_SORT = "stars";
    static final String DEFAULT_ORDER = "desc";

    //Search result github response
    // kết quả trả về của việc timf kiếm trong github
    // nới tìm kiếm  github
    static public class SearchResult {
        @SerializedName("total_count") // hàm nayf lấy total count
        int totalCount;
        @SerializedName("incomplete_results") // lấy incomplete_results trong git
        boolean incompleteResults;
        @SerializedName("items") // hàm này lấy xnag iêtem
                // khởi tạo một m con cho nó
        List<Repo> repos;

    }

    //    Thông tin repo Github
    // dây một cacl  repo
    static public class Repo {
        public int id;
        public String name;
        public Owner owner;
        @SerializedName("html_url")
        public String htmlUrl;
        public String description;
        @SerializedName("stargazers_count")
        public int starsGazers;
        @SerializedName("watchers")
        public int watchers;
        public int forks;
        // của riêng bạn
        public static class Owner {
            String login;
            @SerializedName("avatar_url")
            public String avatarUrl;

        }
    }

    //Retorfit github interface
    interface GitHub {
        // lấy giá trij con trong mảng
        @GET("/search/repositories")
        SearchResult searchRepos(@Query("q") String query,
                                 @Query("sort") String sortBy,
                                 @Query("order") String order,
                                 @Query("page") int start,
                                 @Query("per_page") int perPage);
    }

    /**
     * Get github client.
     *
     * @return Github retrofit interface
     */
    public static GitHub getClient() {
        RestAdapter restAdapter = new RestAdapter.Builder()
                .setEndpoint(API_URL)
                .setLogLevel(RestAdapter.LogLevel.BASIC)
                .build();

        return restAdapter.create(GitHub.class);
    }
}
